name: microproject-bechdel-test Grading
'on':
  workflow_dispatch: {}
jobs:
  autograding:
    name: autograding
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Checkout
      id: sr-checkout
      uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: pip
        cache-dependency-path: microproject-bechdel-test/requirements.txt
    - run: pip install -r microproject-bechdel-test/requirements.txt
    - name: Checkout release repository
      id: release-checkout
      uses: actions/checkout@v3
      with:
        repository: dsdiscovery/microprojects
        ref: microproject-bechdel-test
        path: release
    - name: Checkout cell replacer
      id: cell-replace-checkout
      uses: actions/checkout@v3
      with:
        repository: dsdiscovery/cell-replace
        path: cell-replace
    - name: Run cell-replace
      run: python cell-replace/cell-replace.py microproject-bechdel-test/microproject-bechdel-test.ipynb release/microproject-bechdel-test/microproject-bechdel-test.ipynb
    - name: Generate Test Script
      run: 'python3 -m jupyter2pytest microproject-bechdel-test/microproject-bechdel-test.ipynb "### TEST CASE for (.*)" microproject-bechdel-test/test_microproject-bechdel-test.py '
    - name: Generate Grading Artifacts
      run: cd microproject-bechdel-test && python3 test_microproject-bechdel-test.py && cd ..
    - name: Autograding
      id: autograding
      uses: illinois/autograding@v4
      with:
        path: microproject-bechdel-test/
        test_suite: autograding
        step_summary: true
        all_or_nothing: true
